Repository thankthemaker/rESCueApp, pull requests merged in 2023-10, with the labels that each got.

#47 Local File OTA
  package-lock.json
  package.json
  src/app/update/update.page.html
  src/app/update/update.page.ts
Labels: enhancement

#48 Feature/new lightbar options
  .gitignore
  src/app/models/RescueConf.ts
  src/app/settings/battery/battery.component.html
  src/app/settings/battery/battery.component.ts
  src/app/settings/lights/lights.component.html
  src/app/settings/settings.page.html
  src/app/settings/settings.page.ts
Labels: enhancement

#46 Upgrade to Angular 17 and Ionic 7
  .github/workflows/build-ios-app.yaml
  fastlane/Fastfile
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/appsettings/appsettings.page.html
  src/app/appsettings/notifications/notifications.page.html
  src/app/appsettings/notifications/notifications.page.scss
  src/app/appsettings/odometer/odometer.page.html
  src/app/charts/overview-chart/overview-chart.component.ts
  src/app/device/device.page.html
  src/app/device/device.page.scss
  src/app/device/device.page.ts
  src/app/home/home.page.ts
  src/app/incompatible/incompatible.page.html
  src/app/services/ble.service.ts
  src/app/settings/battery-type/battery-type.component.html
  src/app/settings/battery/battery.component.html
  src/app/settings/canbus/canbus.component.html
  src/app/settings/lights/lights.component.html
  src/app/settings/settings.page.html
  src/app/wizard/wizard.module.ts
  src/app/wizard/wizard.page.html
  src/app/wizard/wizard.page.scss
  src/app/wizard/wizard.page.ts
  src/assets/icon/plug-circle-check.svg
  src/assets/icon/plug-circle-xmark.svg
Labels: framework upgrade

#49 Improvements for BLE and usability, Ionic7 Upgrade fixes
  package-lock.json
  package.json
  src/app/appsettings/appsettings.page.html
  src/app/device/device.page.html
  src/app/device/device.page.ts
  src/app/models/AppSettings.ts
  src/app/services/ble.service.ts
  src/app/services/notification.service.ts
  src/app/settings/battery/battery.component.html
  src/app/settings/canbus/canbus.component.html
  src/app/settings/led-type/led-type.component.html
  src/app/settings/lights/lights.component.html
  src/app/settings/settings.page.html
  src/app/settings/settings.page.ts
  src/app/settings/sounds/sounds.component.html
  src/app/update/update.page.html
  src/app/update/update.page.ts
Labels: bug, enhancement
